### PR TITLE
Update queue_management - new paradigm

### PR DESCRIPTION
**Pull request by ovalle15**

### CODE REVIEW

**Comment by ramy1951** [comment]
@ovalle15 Nice work here Andrea! Just making sure here, did you mean to leave the colab and github links linked to the older version of this notebook?

<td>
<a href="https://colab.research.google.com/github/Labelbox/labelbox-python/blob/develop/examples/project_configuration/queue_management.ipynb" target="_blank">Open In Colab</a>
</td>

<td>
<a href="https://github.com/Labelbox/labelbox-python/tree/develop/examples/project_configuration/queue_management.ipynb" target="_blank">GitHub</a>
</td>

**Comment by ovalle15** [comment]
@ramy1951 but the location of the files is not going to change. We are just replacing content. The links will be pointing to the same file we are modifying, right?

**Comment by ovalle15** [comment]
@ramy1951 tests are failing I am assuming that the commit can't be merged if those tests don't pass right?

**Comment by msokoloff1** [comment]
> 

yeah you don't need to update any of those links

**Review by msokoloff1 — APPROVED** [review]

**Pull request merged**
