### PR TITLE
[AL-1777] Update to Resource Tag test code

### PR DESCRIPTION
**Pull request by jtsodapop**
update to test_project. still leaving as skip as there is an issue wIth tag fetching. also updated resource creation code for better error messaging

### CODE REVIEW

**Comment by jtsodapop** [comment]
Unsure if code has recently been pushed out to change this, but I can only see Organization.resourceTags, and not `resourceTag` which is now causing organization.get_resource_tags to error out. 

changing it to `resourceTags` consistently provides an internal server error. keeping as commented out until this can be addressed.

**Comment by manibox** [comment]
> Unsure if code has recently been pushed out to change this, but I can only see Organization.resourceTags, and not `resourceTag` which is now causing organization.get_resource_tags to error out.
> 
> changing it to `resourceTags` consistently provides an internal server error. keeping as commented out until this can be addressed.

Hi! I believe if we revert a recent PR we pushed (for engineering) week, we can recover for now. https://github.com/Labelbox/intelligence/pull/8014

**Comment by manibox** [comment]
Just merged a revert which bring back the resourceTag endpoint. @jtsodapop lmk if anything else comes up

**Comment by jtsodapop** [comment]
> Just merged a revert which bring back the resourceTag endpoint. @jtsodapop lmk if anything else comes up

Thank you!!

**Comment by msokoloff1** [comment]
Hey can you guys not merge this? I need to get out a hot fix first

**Review by manibox — APPROVED** [review]
lgtm!

**Pull request merged**
