### PR TITLE
Add support of model_run_details to export_v2() for Model Runs

### PR DESCRIPTION
**Pull request by paulnoirel**
Before this PR, the following code will not work correctly because "model_run_details" is not implemented

## Before the PR:

```# load the annotations
model_run = lb_client.get_model_run(model_run_id)

export_params= {
    "data_row_details": True,
    "metadata_fields": True,
    "attachments": True,
    "predictions": True,
    "model_run_details": True
    }
```

Log:

DEBUG:labelbox.client:Query: mutation exportDataRowsInModelRunPyApi($input: ExportDataRowsInModelRunInput!){exportDataRowsInModelRun(input: $input){taskId}}, params: {'input': {'taskName': None, 'filters': {'modelRunId': 'a30daa11-37cd-0875-c05a-40ca39035c1e'}, 'params': {'mediaTypeOverride': None, 'includeAttachments': True, 'includeMetadata': True, 'includeDataRowDetails': True, 'includePredictions': True}, 'streamable': False}}, data None

## After the PR:

For the same code as above, the log now shows the following, with **includeModelRunDetails** now included

DEBUG:labelbox.client:Query: mutation exportDataRowsInModelRunPyApi($input: ExportDataRowsInModelRunInput!){exportDataRowsInModelRun(input: $input){taskId}}, params: {'input': {'taskName': None, 'filters': {'modelRunId': 'a30daa11-37cd-0875-c05a-40ca39035c1e'}, 'params': {'mediaTypeOverride': None, 'includeAttachments': True, 'includeMetadata': True, 'includeDataRowDetails': True, 'includePredictions': True, '**includeModelRunDetails**': True}, 'streamable': False}}, data None

### CODE REVIEW

**Review by vbrodsky — COMMENTED** [review]
I've gathered that previously we weren't including the option to export model run details directly from our SDK. However, it seems that with the recent changes, this functionality is now available. Is my understanding correct that we can now export model run details through the SDK?

If that's the case, would you be able to incorporate tests for this new feature into our SDK integration test suite? This could be done either as part of the current PR or as a quick follow-up. Having this as a part of our sdk integration tests is important for maintaining the robustness of our SDK.

**Comment by paulnoirel** [comment]
Thanks, @vbrodsky!
You are correct. Model Run Details was introduced "recently" to the point that the current documentation describes it as a beta feature. 
I will add a unit test for the specific parameter to this PR soon.

**Comment by vbrodsky** [comment]
@paulnoirel I have already merged a fix for this https://labelbox.atlassian.net/browse/PLT-74 I will look though at your test here

**Comment by vbrodsky** [comment]
The pointer to the test is a good one, as I was wondering how to add my change to the integration test suite. I will add a story for that to our backlog

**Comment by paulnoirel** [comment]
Duplicate with PLT-74

**Pull request closed without merging**
