### PR TITLE
[SN-96,97] update composite mask notebook, and data row metadata notebook

### PR DESCRIPTION
**Pull request by ovalle15**
- Added bulk export with data row identifiers 
- Added bulk delete with data row identifiers
- Updated composite mask export text

### CODE REVIEW

**Comment by lb-pno** [comment]
@ovalle15 Please ensure double or single quotes are consistent in notebooks.

**Review by lb-pno — APPROVED** [review]
LGTM

**Comment by ovalle15** [comment]
Thank you @paulnoirel

**Review by mina-ebeid — APPROVED** [review]
Looks good on my end!

**Pull request merged**
