### PR TITLE
[SN-89] Remove/ update integration notebooks

### PR DESCRIPTION
**Pull request by Gabefire**

### CODE REVIEW

**Comment by Gabefire** [comment]
removed examples/integrations/tlt/labelbox_upload.ipynb since the urls are broken and the dataset it needed was 6 gb. Also it just goes over a basic demo of labelbox which we have plenty of

**Comment by Gabefire** [comment]
Removed

**Comment by Gabefire** [comment]
Made the decision to delete the databricks integrations they require Java runtime to work which makes them tricky, labelsparks is currently out of date and labelsparks has notebook examples of its own. If you disagree let me know.

**Comment by Gabefire** [comment]
removed detectron notebooks since they depending on coco serializer to work and we have no plans of fixing its many issues. Can add back later if/ when coco stuff gets fixed

**Comment by Gabefire** [comment]
Improved huggingface.ipynb to make it cleaner and added some mulitthreading to help with the image downloads. Honestly not sure if this one works or not it seems it does now I need you to check this one

**Comment by Gabefire** [comment]
Once this is improved we need to find the broken links if they were used at all. https://docs.labelbox.com/page/tutorials and we need to update the readme

**Review by tomislav-peharda — APPROVED** [review]

**Pull request merged**
