### PR TITLE
Bump dateutil max version

### PR DESCRIPTION
**Pull request by colonelpanic8**
# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Document change (fix typo or modifying any markdown files, code comments or anything in the examples folder only)

## All Submissions

- [ ] Have you followed the guidelines in our Contributing document?
- [ ] Have you provided a description?
- [ ] Are your changes properly formatted?

## New Feature Submissions

- [ ] Does your submission pass tests?
- [ ] Have you added thorough tests for your new feature?
- [ ] Have you commented your code, particularly in hard-to-understand areas?
- [ ] Have you added a Docstring?

## Changes to Core Features

- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you successfully run tests with your changes locally?
- [ ] Have you updated any code comments, as applicable?

### CODE REVIEW

**Comment by adrian-chang** [comment]
Hey @colonelpanic8

So we use `rye` for development, not `poetry` so the PR as is won't be able to be approved. 

Please read this for further details (https://github.com/Labelbox/labelbox-python/blob/develop/CONTRIBUTING.md).

We'll take care of the dateutil bump, but what is the need for a head version of OpenCV? We're not aware of any use case of the SDK needing a head version.

**Comment by colonelpanic8** [comment]
@adrian-chang yeah sorry, i forgot i had made this pr and i was using this pr to mess around with a git build.

the original change was just a bump tho:

https://github.com/Labelbox/labelbox-python/pull/1716/commits/071b3960580ab4889626337f49de8f9dfd5a4ed2

**Comment by colonelpanic8** [comment]
I adjusted things so that my poetry stuff is in another branch.

**Review by adrian-chang — APPROVED** [review]

**Comment by adrian-chang** [comment]
I'm going to merge this in ... given a library bump, our GHActions will have to be updated to address remote forks, thanks though!

**Pull request merged**
