### PR TITLE
[AL-0] Remove custom embeddings

### PR DESCRIPTION
**Pull request by kkim-labelbox**
Remove references to custom embeddings in SDK

### CODE REVIEW

**Comment by whistler** [comment]
Why do we not support custom embeddings anymore? Is this a breaking change?

**Comment by kkim-labelbox** [comment]
@whistler Custom embeddings have been removed from the system already. Users currently cannot create custom embeddings metadata, so this isn't a breaking change. I got the sign off from @karenkyang, @sqlboy and @tomislav-peharda to delete it from the SDK

**Review by whistler — APPROVED** [review]

**Comment by manuaero** [comment]
FYI: We will be soon supporting custom embeddings in SDK again (once ADV ships).

**Review by tomislav-peharda — APPROVED** [review]

**Comment by kkim-labelbox** [comment]
Ongoing discussion on whether to go ahead with this change, because custom embeddings will be reintroduced. However, we do not yet know whether we want to reintroduce it as a dataRow metadata, or its own class.

**Comment by kkim-labelbox** [comment]
Closing PR, since custom embedding will be part of dataRow metadata when it's shipped via ADV.

**Pull request closed without merging**
